branches:
  only:
    - master

language: android
sudo: false

android:
  components:
    - build-tools-22.0.1

    - android-21
    - doc-MNC

    - extra-android-support
    - extra-android-m2repository

    - sys-img-x86-android-21

before_script:
    - echo no | android create avd --force -n test -t android-21 --abi x86
    - emulator -avd test -no-skin -no-audio -no-window &
    - android-wait-for-emulator
    - adb shell input keyevent 82 &

script:
    - ./gradlew clean connectedCheck --info

cache:
  directories:
    - $HOME/.gradle
    - $HOME/.m2/repository
